package com.sapeadita.serviceImpl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

import com.sapeadita.bean.UsuarioBean;
import com.sapeadita.dao.LoginDao;
import com.sapeadita.service.EmailService;

import javax.mail.internet.MimeMessage;

@Component
public class EmailServiceImpl implements EmailService{
	
	@Autowired
	LoginDao loginDao;
	
	@Autowired
    private JavaMailSender emailSender;

	@Override
	public void enviarEmailVerificacion(UsuarioBean usuario) throws Exception {
		MimeMessage mimeMessage = emailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(mimeMessage);

		String html = "<!doctype html>\n" +
                "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"\n" +
                "      xmlns:th=\"http://www.thymeleaf.org\">\n" +
                "<head>\n" +
                "    <meta charset=\"UTF-8\">\n" +
                "    <meta name=\"viewport\"\n" +
                "          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n" +
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
                "    <title>Email</title>\n" +
                "</head>\n" +
//                "<body>\n" +
//                "<div>Welcome <b>" + "alanchumpitaz@gmail.com" + "</b></div>\n" +
//                "\n" +
//                "<div> Your username is <b>" + "alanchumpitaz@gmail.com" + "</b></div>\n" +
//                "</body>\n" +
                
            
                 "<body>\r\n"
                 + "   <div class=\"es-wrapper-color\">\r\n"
                 + "      <!--[if gte mso 9]>\r\n"
                 + "      <v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
                 + "         <v:fill type=\"tile\" color=\"#f7f7f7\"></v:fill>\r\n"
                 + "      </v:background>\r\n"
                 + "      <![endif]--> \r\n"
                 + "      <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "         <tbody>\r\n"
                 + "            <tr>\r\n"
                 + "               <td class=\"esd-email-paddings ui-droppable\" valign=\"top\">\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content esd-header-popover ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr> \r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-header ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"es-adaptive esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88593\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "                              <div class=\"esd-structure-type\">\r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-header-body\" style=\"background-color: rgb(61, 92, 163);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#3d5ca3\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p20b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-color: rgb(61, 92, 163);\" bgcolor=\"#3d5ca3\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <!--[if mso]>\r\n"
                 + "                                          <table width=\"560\" cellpadding=\"0\" \r\n"
                 + "                                             cellspacing=\"0\">\r\n"
                 + "                                             <tr>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"270\" align=\"left\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-m-p0l es-m-txt-c esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"left\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "                                                                           <div class=\"esd-block-btn \">\r\n"
                 + "                                                                           </div>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                                <td width=\"20\"></td>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                             </tr>\r\n"
                 + "                                          </table>\r\n"
                 + "                                          <![endif]-->\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: rgb(250, 250, 250);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fafafa\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p40b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-repeat: no-repeat;\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h1 style=\"color: #333333; font-family: lora, georgia, 'times new roman', serif; font-size: 50px;\"><em>Sapeadita</em></h1>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p10t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h3 style=\"color: #333333;\">Gracias por registrarse - confirmar código.</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>We teach classes in everything from business to medicine.</p>\r\n"
//                 + "                                                                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "															<tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"

                 + "																  <h3 style=\"color: rgb(61, 92, 163);\">Código de verificación: "+usuario.getCodigoValidacion()+"</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "	\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-custom-block-id=\"88591\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <div class=\"esd-add-stripe\">\r\n"
                 + "                                 <a><span class=\"es-icon-plus\"></span></a>\r\n"
                 + "                                \r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p15t es-p15b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" style=\"background-color: black;\" bgcolor=\"#f7c052\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "      \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "   \r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/35681527588356492.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td esdev-links-color=\"#ffffff\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff;\"><a target=\"_blank\" style=\"color: #ffffff; font-size: 18px;\" href=\"mailto:your@mail.com\">your@mail.com</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "     \r\n"
                 + "                                                   <table class=\"es-right\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "    \r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/50681527588357616.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-links-color=\"#ffffff\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff; font-size: 16px;\"><a target=\"_blank\" style=\"font-size: 16px; color: rgb(255, 255, 255);\" href=\"tel:123456789\">123456789</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88592\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                             \r\n"
                 + "                              <table class=\"es-footer-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "  \r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p5t es-p10b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"580\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p5t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <h5 style=\"color: #666666;\">Contact us: <a target=\"_blank\" href=\"tel:123456789\">123456789</a> | <a target=\"_blank\" href=\"mailto:your@mail.com\">your@mail.com</a></h5>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td align=\"center\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>This daily newsletter was sent to <a target=\"_blank\" href=\"mailto:info@name.com\">info@edu.com</a> from company name because you subscribed.</p>\r\n"
//                 + "                                                                  <p>If you would not like to receive this email <a target=\"_blank\" class=\"unsubscribe\" href=\"\">unsubscribe here</a>.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"esd-footer-popover es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                          \r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: transparent;\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p30t es-p30b es-p20r es-p20l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-img-prev-src=\"\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-image es-infoblock made_with esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <a target=\"_blank\" href=\"https://viewstripo.email/?utm_source=templates&amp;utm_medium=email&amp;utm_campaign=education&amp;utm_content=trigger_newsletter\"><img src=\"https://tlr.stripocdn.email/content/guids/cab_pub_7cbbc409ec990f19c78c75bd1e06f215/images/78411525331495932.png\" alt=\"\" style=\"display: block;\" width=\"125\"></a>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "               </td>\r\n"
                 + "            </tr>\r\n"
                 + "         </tbody>\r\n"
                 + "      </table>\r\n"
                 + "   </div>\r\n"
                 + "</body>"+

                

                "</html>\n";
		
		SimpleMailMessage message = new SimpleMailMessage(); 
		helper.setFrom("noreply@baeldung.com");
        helper.setTo(usuario.getEmail()); 
        helper.setSubject(usuario.getUsername()+" Bienvenido a Sapeadita"); 
        helper.setText(html,true);

        emailSender.send(mimeMessage);
		
	}
	
	@Override
	public void enviarEmailConfirmacion(UsuarioBean usuario) throws Exception {
		MimeMessage mimeMessage = emailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(mimeMessage);

		String html = "<!doctype html>\n" +
                "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"\n" +
                "      xmlns:th=\"http://www.thymeleaf.org\">\n" +
                "<head>\n" +
                "    <meta charset=\"UTF-8\">\n" +
                "    <meta name=\"viewport\"\n" +
                "          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n" +
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
                "    <title>Email</title>\n" +
                "</head>\n" +
            
                 "<body>\r\n"
                 + "   <div class=\"es-wrapper-color\">\r\n"
                 + "      <!--[if gte mso 9]>\r\n"
                 + "      <v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
                 + "         <v:fill type=\"tile\" color=\"#f7f7f7\"></v:fill>\r\n"
                 + "      </v:background>\r\n"
                 + "      <![endif]--> \r\n"
                 + "      <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "         <tbody>\r\n"
                 + "            <tr>\r\n"
                 + "               <td class=\"esd-email-paddings ui-droppable\" valign=\"top\">\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content esd-header-popover ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr> \r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-header ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"es-adaptive esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88593\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "                              <div class=\"esd-structure-type\">\r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-header-body\" style=\"background-color: rgb(61, 92, 163);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#3d5ca3\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p20b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-color: rgb(61, 92, 163);\" bgcolor=\"#3d5ca3\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <!--[if mso]>\r\n"
                 + "                                          <table width=\"560\" cellpadding=\"0\" \r\n"
                 + "                                             cellspacing=\"0\">\r\n"
                 + "                                             <tr>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"270\" align=\"left\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-m-p0l es-m-txt-c esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"left\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "                                                                           <div class=\"esd-block-btn \">\r\n"
                 + "                                                                           </div>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                                <td width=\"20\"></td>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                             </tr>\r\n"
                 + "                                          </table>\r\n"
                 + "                                          <![endif]-->\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: rgb(250, 250, 250);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fafafa\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p40b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-repeat: no-repeat;\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h1 style=\"color: #333333; font-family: lora, georgia, 'times new roman', serif; font-size: 50px;\"><em>Sapeadita</em></h1>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p10t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h3 style=\"color: #333333;\">Bienvenido, registro exitoso.</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>We teach classes in everything from business to medicine.</p>\r\n"
//                 + "                                                                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "															<tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"

                 + "																  <h3 style=\"color: rgb(61, 92, 163);\">Usuario : "+usuario.getUsername()+"</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "	\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-custom-block-id=\"88591\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <div class=\"esd-add-stripe\">\r\n"
                 + "                                 <a><span class=\"es-icon-plus\"></span></a>\r\n"
                 + "                                \r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p15t es-p15b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" style=\"background-color: black;\" bgcolor=\"#f7c052\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "      \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "   \r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/35681527588356492.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td esdev-links-color=\"#ffffff\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff;\"><a target=\"_blank\" style=\"color: #ffffff; font-size: 18px;\" href=\"mailto:your@mail.com\">your@mail.com</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "     \r\n"
                 + "                                                   <table class=\"es-right\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "    \r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/50681527588357616.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-links-color=\"#ffffff\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff; font-size: 16px;\"><a target=\"_blank\" style=\"font-size: 16px; color: rgb(255, 255, 255);\" href=\"tel:123456789\">123456789</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88592\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                             \r\n"
                 + "                              <table class=\"es-footer-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "  \r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p5t es-p10b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"580\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p5t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <h5 style=\"color: #666666;\">Contact us: <a target=\"_blank\" href=\"tel:123456789\">123456789</a> | <a target=\"_blank\" href=\"mailto:your@mail.com\">your@mail.com</a></h5>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td align=\"center\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>This daily newsletter was sent to <a target=\"_blank\" href=\"mailto:info@name.com\">info@edu.com</a> from company name because you subscribed.</p>\r\n"
//                 + "                                                                  <p>If you would not like to receive this email <a target=\"_blank\" class=\"unsubscribe\" href=\"\">unsubscribe here</a>.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"esd-footer-popover es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                          \r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: transparent;\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p30t es-p30b es-p20r es-p20l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-img-prev-src=\"\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-image es-infoblock made_with esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <a target=\"_blank\" href=\"https://viewstripo.email/?utm_source=templates&amp;utm_medium=email&amp;utm_campaign=education&amp;utm_content=trigger_newsletter\"><img src=\"https://tlr.stripocdn.email/content/guids/cab_pub_7cbbc409ec990f19c78c75bd1e06f215/images/78411525331495932.png\" alt=\"\" style=\"display: block;\" width=\"125\"></a>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "               </td>\r\n"
                 + "            </tr>\r\n"
                 + "         </tbody>\r\n"
                 + "      </table>\r\n"
                 + "   </div>\r\n"
                 + "</body>"+

                

                "</html>\n";
		
		SimpleMailMessage message = new SimpleMailMessage(); 
		helper.setFrom("noreply@baeldung.com");
		helper.setTo(usuario.getEmail()); 
        helper.setSubject(usuario.getUsername()+" Bienvenido a Sapeadita"); 
        helper.setText(html,true);

        emailSender.send(mimeMessage);
		
	}
	
	@Override
	public void enviarEmailRecuperacion(UsuarioBean usuario) throws Exception {
		MimeMessage mimeMessage = emailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(mimeMessage);

		String html = "<!doctype html>\n" +
                "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"\n" +
                "      xmlns:th=\"http://www.thymeleaf.org\">\n" +
                "<head>\n" +
                "    <meta charset=\"UTF-8\">\n" +
                "    <meta name=\"viewport\"\n" +
                "          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n" +
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
                "    <title>Email</title>\n" +
                "</head>\n" +
            
                 "<body>\r\n"
                 + "   <div class=\"es-wrapper-color\">\r\n"
                 + "      <!--[if gte mso 9]>\r\n"
                 + "      <v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
                 + "         <v:fill type=\"tile\" color=\"#f7f7f7\"></v:fill>\r\n"
                 + "      </v:background>\r\n"
                 + "      <![endif]--> \r\n"
                 + "      <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "         <tbody>\r\n"
                 + "            <tr>\r\n"
                 + "               <td class=\"esd-email-paddings ui-droppable\" valign=\"top\">\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content esd-header-popover ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr> \r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-header ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"es-adaptive esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88593\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "                              <div class=\"esd-structure-type\">\r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-header-body\" style=\"background-color: rgb(61, 92, 163);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#3d5ca3\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p20b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-color: rgb(61, 92, 163);\" bgcolor=\"#3d5ca3\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <!--[if mso]>\r\n"
                 + "                                          <table width=\"560\" cellpadding=\"0\" \r\n"
                 + "                                             cellspacing=\"0\">\r\n"
                 + "                                             <tr>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"270\" align=\"left\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-m-p0l es-m-txt-c esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"left\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "                                                                           <div class=\"esd-block-btn \">\r\n"
                 + "                                                                           </div>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                                <td width=\"20\"></td>\r\n"
                 + "                                                <td width=\"270\" valign=\"top\">\r\n"
                 + "                                                   <![endif]--> \r\n"
                 + "\r\n"
                 + "                                                   <!--[if mso]>\r\n"
                 + "                                                </td>\r\n"
                 + "                                             </tr>\r\n"
                 + "                                          </table>\r\n"
                 + "                                          <![endif]-->\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: rgb(250, 250, 250);\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fafafa\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p20t es-p40b es-p20r es-p20l esd-frame esdev-disable-select esd-hover\" style=\"background-repeat: no-repeat;\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h1 style=\"color: #333333; font-family: lora, georgia, 'times new roman', serif; font-size: 50px;\"><em>Sapeadita</em></h1>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p10t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
                 + "                                                                  <h3 style=\"color: #333333;\">Contraseña recuperada.</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>We teach classes in everything from business to medicine.</p>\r\n"
//                 + "                                                                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "															<tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p20b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"

                 + "																  <h3 style=\"color: rgb(61, 92, 163);\">Nueva contraseña : "+usuario.getPassword()+"</h3>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "	\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-custom-block-id=\"88591\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                              <div class=\"esd-add-stripe\">\r\n"
                 + "                                 <a><span class=\"es-icon-plus\"></span></a>\r\n"
                 + "                                \r\n"
                 + "                              </div>\r\n"
                 + "                              <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p15t es-p15b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" style=\"background-color: black;\" bgcolor=\"#f7c052\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "      \r\n"
                 + "                                                   <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"es-m-p20b esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "   \r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/35681527588356492.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td esdev-links-color=\"#ffffff\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff;\"><a target=\"_blank\" style=\"color: #ffffff; font-size: 18px;\" href=\"mailto:your@mail.com\">your@mail.com</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "     \r\n"
                 + "                                                   <table class=\"es-right\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\">\r\n"
                 + "                                                      <tbody class=\"ui-droppable\">\r\n"
                 + "                                                         <tr class=\"ui-draggable\">\r\n"
                 + "                                                            <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"180\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                               <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                                  <tbody class=\"ui-droppable\">\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-image es-p5b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "    \r\n"
                 + "                                                                           <a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_66498ea076b5d00c6f9553055acdb37a/images/50681527588357616.png\" alt=\"\" style=\"display: block;\" width=\"24\"></a>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                     <tr class=\"ui-draggable\">\r\n"
                 + "                                                                        <td class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-links-color=\"#ffffff\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                           <p style=\"color: #ffffff; font-size: 16px;\"><a target=\"_blank\" style=\"font-size: 16px; color: rgb(255, 255, 255);\" href=\"tel:123456789\">123456789</a></p>\r\n"
                 + "                                                                        </td>\r\n"
                 + "                                                                     </tr>\r\n"
                 + "                                                                  </tbody>\r\n"
                 + "                                                               </table>\r\n"
                 + "                                                            </td>\r\n"
                 + "                                                         </tr>\r\n"
                 + "                                                      </tbody>\r\n"
                 + "                                                   </table>\r\n"
                 + "\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer ui-draggable\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esdev-disable-select esd-hover\" align=\"center\" esd-custom-block-id=\"88592\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                             \r\n"
                 + "                              <table class=\"es-footer-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "  \r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p5t es-p10b es-p10r es-p10l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"580\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-text es-p5t es-p10b esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <h5 style=\"color: #666666;\">Contact us: <a target=\"_blank\" href=\"tel:123456789\">123456789</a> | <a target=\"_blank\" href=\"mailto:your@mail.com\">your@mail.com</a></h5>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td align=\"center\" class=\"esd-block-text esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" esd-handler-name=\"textElementHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <p>This daily newsletter was sent to <a target=\"_blank\" href=\"mailto:info@name.com\">info@edu.com</a> from company name because you subscribed.</p>\r\n"
//                 + "                                                                  <p>If you would not like to receive this email <a target=\"_blank\" class=\"unsubscribe\" href=\"\">unsubscribe here</a>.</p>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "                  <table class=\"esd-footer-popover es-content ui-draggable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
                 + "                     <tbody>\r\n"
                 + "                        <tr>\r\n"
                 + "                           <td class=\"esd-stripe esd-frame esd-hover esdev-disable-select\" align=\"center\" esd-handler-name=\"stripeBlockHandler\">\r\n"
                 + "\r\n"
                 + "                          \r\n"
                 + "                              <table class=\"es-content-body\" style=\"background-color: transparent;\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
                 + "                                 <tbody class=\"ui-droppable\">\r\n"
                 + "                                    <tr class=\"ui-draggable\">\r\n"
                 + "                                       <td class=\"esd-structure es-p30t es-p30b es-p20r es-p20l esd-frame esd-hover esdev-disable-select\" align=\"left\" esd-img-prev-src=\"\" esd-handler-name=\"structureBlockHandler\">\r\n"
                 + "\r\n"
                 + "                                          <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                             <tbody class=\"ui-droppable\">\r\n"
                 + "                                                <tr class=\"ui-draggable\">\r\n"
                 + "                                                   <td class=\"esd-container-frame esd-frame esd-hover esdev-disable-select\" width=\"560\" valign=\"top\" align=\"center\" esd-handler-name=\"containerHandler\">\r\n"
                 + "\r\n"
                 + "                                                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
                 + "                                                         <tbody class=\"ui-droppable\">\r\n"
                 + "                                                            <tr class=\"ui-draggable\">\r\n"
                 + "                                                               <td class=\"esd-block-image es-infoblock made_with esd-frame esd-hover esdev-disable-select esd-draggable esd-block\" align=\"center\" style=\"font-size:0\" esd-handler-name=\"imgBlockHandler\">\r\n"
                 + "\r\n"
//                 + "                                                                  <a target=\"_blank\" href=\"https://viewstripo.email/?utm_source=templates&amp;utm_medium=email&amp;utm_campaign=education&amp;utm_content=trigger_newsletter\"><img src=\"https://tlr.stripocdn.email/content/guids/cab_pub_7cbbc409ec990f19c78c75bd1e06f215/images/78411525331495932.png\" alt=\"\" style=\"display: block;\" width=\"125\"></a>\r\n"
                 + "                                                               </td>\r\n"
                 + "                                                            </tr>\r\n"
                 + "                                                         </tbody>\r\n"
                 + "                                                      </table>\r\n"
                 + "                                                   </td>\r\n"
                 + "                                                </tr>\r\n"
                 + "                                             </tbody>\r\n"
                 + "                                          </table>\r\n"
                 + "                                       </td>\r\n"
                 + "                                    </tr>\r\n"
                 + "                                 </tbody>\r\n"
                 + "                              </table>\r\n"
                 + "                           </td>\r\n"
                 + "                        </tr>\r\n"
                 + "                     </tbody>\r\n"
                 + "                  </table>\r\n"
                 + "               </td>\r\n"
                 + "            </tr>\r\n"
                 + "         </tbody>\r\n"
                 + "      </table>\r\n"
                 + "   </div>\r\n"
                 + "</body>"+

                

                "</html>\n";
		
		SimpleMailMessage message = new SimpleMailMessage(); 
		helper.setFrom("noreply@baeldung.com");
		helper.setTo(usuario.getEmail()); 
        helper.setSubject(usuario.getUsername()+" Bienvenido a Sapeadita"); 
        helper.setText(html,true);

        emailSender.send(mimeMessage);
		
	}

}
